// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD8hXb8LgScXEXEiAl80URplolkIAzV28',
    appId: '1:801831492617:ios:7eff7ed1c72da15ff4acd8',
    messagingSenderId: '801831492617',
    projectId: 'tracker-flutter-55384',
    storageBucket: 'tracker-flutter-55384.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD8hXb8LgScXEXEiAl80URplolkIAzV28',
    appId: '1:801831492617:ios:7eff7ed1c72da15ff4acd8',
    messagingSenderId: '801831492617',
    projectId: 'tracker-flutter-55384',
    storageBucket: 'tracker-flutter-55384.firebasestorage.app',
    iosBundleId: 'com.example.trackerFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEihFW2NWhEicfMRr5KRTTqFVruB8toag',
    appId: '1:801831492617:web:f7e82fb00fdef0daf4acd8',
    messagingSenderId: '801831492617',
    projectId: 'tracker-flutter-55384',
    authDomain: 'tracker-flutter-55384.firebaseapp.com',
    storageBucket: 'tracker-flutter-55384.firebasestorage.app',
    measurementId: 'G-RWR2M3BYZD',
  );

  static const FirebaseOptions windows = web;
}
